# Generated by Django 2.2.4 on 2019-08-22 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190822_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='category_id',
            new_name='category',
        ),
    ]
